### PR TITLE
added scroll function for about section with smooth scroll in css

### LINKED ISSUE #52: Scroll down to the "about" section when clicking the "about" link
**Is your feature request related to a problem? Please describe.**
should Scroll down to the "about" section when clicking the "about" link

**Describe the solution you'd like**
Use the basic HTML

**Additional context**
Screenshot 2023-03-11 061406

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by aayushdhakal**
## Purpose
The purpose of this Pr is to Fix #52

## Approach
Assigned id to the scrolled to location and added id to the about section of the navigation bar.

## ScreenShots
about scroll

## Learning 
About to create links to sections on the same page in HTML.

### CODE REVIEW

**Comment by Tharindu37** [comment]
WhatsApp Image 2023-03-06 at 08 51 39

@aayushdhakal Edit the PR following this

**Comment by aayushdhakal** [comment]
I have updated the PR can you please look into it.

**Comment by aayushdhakal** [comment]
I have updated the PR can you please look into it.

**Comment by Tharindu37** [comment]
@aayushdhakal Ok, I will look

**Comment by Tharindu37** [comment]
@aayushdhakal Thank you, great work

**Pull request merged**
