### PR TITLE
Fixed welcome text - Issue #35

### LINKED ISSUE #35: Make the welcome text section responsive
**Describe the bug**
The welcome text is not responsive.

**Expected behavior**
The welcome text is not responsive.

**Screenshots**
Screenshot 2023-02-26 081731

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by emergenitro**
## Purpose

The purpose of this PR is to fix #35 

## Approach
Improved the welcome text by making it flex text in mobile devices and centers itself, however, is positioned absolute (as you wanted) on larger screens. I also changed the background into a much more desirable way in CSS.

### Screenshots
Laptop:
image

Mobile:
image

### CODE REVIEW

**Comment by Tharindu37** [comment]
@emergenitro please comment the issue that you would like to work.

**Comment by emergenitro** [comment]
Ah sorry about that, I just did it because it seemed like a small issue. I will comment from now on. I'm fairly new to contributions so again, sorry about that!

**Comment by Tharindu37** [comment]
> 

it's Ok

**Comment by Tharindu37** [comment]
@emergenitro Can you decrease the margin-bottom

**Comment by Tharindu37** [comment]
@emergenitro Can you Update the PR Screenshots

**Comment by Tharindu37** [comment]
@emergenitro Thank you, good job

**Pull request merged**
