### PR TITLE
Move arrow.gif file to assets folder

### LINKED ISSUE #136: arrow.gif file move to the assets folder
**Is your feature request related to a problem? Please describe.**
All images should include in one folder

**Describe the solution you'd like**
arrow.gif file move to the assets folder

**Additional context**
Resolve all outstanding issues by moving the file.

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by rohit-rambade**
## Purpose

The purpose of this PR is to fix #136

### CODE REVIEW

**Comment by Tharindu37** [comment]
@rohit-rambade Thank you

**Comment by rohit-rambade** [comment]
Welcome @Tharindu37. I am interested in contributing to your repository  and have identified multiple issues that I would like to work on. Before I begin working on these issues, I want your permission to do so.

**Comment by Tharindu37** [comment]
@rohit-rambade Sure, You can add issues

**Comment by rohit-rambade** [comment]
i need to get assigned in every issues ? or i can make direct PR.
@Tharindu37

**Comment by Tharindu37** [comment]
@rohit-rambade Yes, you need to get assigned to every issue.

**Pull request merged**
