### PR TITLE
Add style changes to styles.css

### LINKED ISSUE #54: Decrease the margin-bottom of the "welcome text"
**Describe the bug**
"Welcome text" is not good in the mobile phone view

**Screenshots**
Screenshot 2023-03-11 104055

**Additional context**
the new position of "welcome text"
Screenshot 2023-03-11 104055

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by AK4266**
## Purpose

The purpose of this PR is to fix  #54<issue-number>

## Approach

just need to add top property to the existing jquery 

### Screenshots

Screenshot 2023-03-11 134938

### CODE REVIEW

**Comment by Tharindu37** [comment]
@AK4266 Pleace comment to the issue that you like to work before do the issue

**Comment by AK4266** [comment]
yes sir, sorry about that. Iam new to the open source.

**Comment by AK4266** [comment]
I'll keep that in mind next time

**Comment by Tharindu37** [comment]
@AK4266 It’s ok.

**Comment by Tharindu37** [comment]
@AK4266 Ok, comment now

**Pull request merged**
