### PR TITLE
Update available link in the README file

### LINKED ISSUE #127: Update the Readme.md file
**Is your feature request related to a problem? Please describe.**
The ProSolution website deployed on another server. therefore we should update the Readme file with the new available link

**Describe the solution you'd like**
Add the new available link as follows.
Available at : [https://pro-solutions.vercel.app/](url)

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by Yvad60**
## Purpose

The purpose of this PR is to fix #127

## Approach
Edited the README.md file to include the new available link https://pro-solutions.vercel.app/

### CODE REVIEW

**Comment by Tharindu37** [comment]
@Yvad60 Can you update the PR with a Screenshot?

**Comment by Tharindu37** [comment]
@Yvad60 Both links are required.

**Comment by Yvad60** [comment]
> @Yvad60 Can you update the PR with a Screenshot?

@Tharindu37 do you mean the screenshot of the new available link page (ui)

**Comment by Tharindu37** [comment]
@Yvad60 I mean the screenshot of the new README file

**Comment by Tharindu37** [comment]
@Yvad60 Now it's ok, I will merge it

**Comment by Tharindu37** [comment]
@Yvad60 Thank you

**Pull request merged**
