### PR TITLE
Created Solution Banner

### PR DESCRIPTION
**Pull request by AK4266**
## Purpose

The purpose of this PR is to fix ##63<issue-number>
The issue to create a solution banner as shown is created.

## Approach

Used background-image for the solutions image and used linear gradient for light black shade on the image

### Screenshots

Screenshot 2023-03-13 182632

### CODE REVIEW

**Comment by Tharindu37** [comment]
@AK4266 Can you compress the image because the image is not render?

**Comment by Tharindu37** [comment]
@AK4266 Ok, go ahead

**Comment by Tharindu37** [comment]
@AK4266 Don't want new PR. You Change the image and commit it. now you push the code to your working branch.

**Comment by Tharindu37** [comment]
@AK4266 so that your PR will be updated automatically

**Comment by Tharindu37** [comment]
@AK4266 Delete the "solution" and "solution-min" images

**Comment by Tharindu37** [comment]
@AK4266 Now you can commit and push the code into the current branch

**Comment by Tharindu37** [comment]
@AK4266 Good, Thank you

**Comment by AK4266** [comment]
No problem.

**Pull request merged**
